export const lightTheme = {
  colors: {
    receipeInstructionsColor: "#767697",
    nameColor: "#9b5902",
    highlightColor: "#a06620",
    recipenamecontainerBackgroundColor: "bisque",
    recipenameColor: "#6f091f",
    featurenameColor: "#a39a9a",
    recipetypeColor: "rgb(148 81 86)",
    recipeinstructionsColor: "#767697",
    caloriesratingreviewscontainerColor: "brown",
    tagscontainerColor: "blue",
    topcontainerColor: "white",
    topcontainerBackgroundColor: "#7c3030",
    loadercontainerColor: "rgba(255, 255, 255, 0.8)",
    loaderBorderColor: "#f3f3f3",
    loaderBordertopColor: "#3498db",
    appbackgroundcolor: "white",
    linksColor: "#074ab5",
    headingColor: "black",
    fontawesomeiconColor: "black",
    recipecontainerbordercolor: "black",
  },
};
export const darkTheme = {
  colors: {
    recipecontainerbordercolor: "white",
    fontawesomeiconColor: "white",
    headingColor: "white",
    receipeInstructionsColor: "#7F7F7F",
    nameColor: "red",
    highlightColor: "#FF7F50",
    recipenamecontainerBackgroundColor: "#9df593",
    recipenameColor: "red",
    featurenameColor: "red",
    recipetypeColor: "red",
    recipeinstructionsColor: "#A0A0A0",
    caloriesratingreviewscontainerColor: "#8B4513",
    tagscontainerColor: "#4682B4",
    topcontainerColor: "white",
    topcontainerBackgroundColor: "#6f86f7",
    loadercontainerColor: "rgba(79, 79, 79, 0.8)",
    loaderBorderColor: "#FFFFFF",
    loaderBordertopColor: "#4682B4",
    appbackgroundcolor: "black",
    linksColor: "white",
  },
};
