export const theme = {
  colors: {
    receipeInstructionsColor: "#767697",
    nameColor: "#9b5902",
    highlightColor: "#a06620",
    recipenamecontainerBackgroundColor: "bisque",
    recipenameColor: "#6f091f",
    featurenameColor: "#a39a9a",
    recipetypeColor: "rgb(148 81 86)",
    recipeinstructionsColor: "#767697",
    caloriesratingreviewscontainerColor: "brown",
    tagscontainerColor: "blue",
    topcontainerColor: "white",
    topcontainerBackgroundColor: "#7c3030",
    loadercontainerColor: "rgba(255, 255, 255, 0.8)",
    loaderBorderColor: "#f3f3f3",
    loaderBordertopColor: "#3498db",
    primaryappColor: "hotpink",
    backgroundappColor: "lightgrey",
  },
};
